### ISSUE TITLE
Implement Media Changes

### ISSUE THREAD

**Issue by ElliottAYoung** [CIMUN/SKYNet#17]
Press Releases:
– Can be sent out by Cabinets and Media only.
	> Media, POs and Admin can access form.
	> If Media sends out a PR:
		It goes straight to the Ticker and CIMUN Live.
		Sims is notified and can acknowledge it.
	> If a PO send out a PR:
		It goes straight to the Ticker and CIMUN Live.
		Sims and Media are notified and can acknowledge it.
– IPD’s Chief Communications Officer will monitor PRs for IPD delegates to use in stories.

Press Conferences:
– Sims Focused Media Event
> TK SOMEONE  CONFIRM THIS PROCESS PLEASE - JC 

CNN Scripts:
– Scripts will be sent from Sims to CNN
	> Notifications will be send to USG-M and EIC, who can acknowledge it.
	> IPD’s Chief Communications Officer will be responsible for coordinating all leaks from Sims. Should there be a Sims to Media form for this?

Shit that I'm actually adding to SKYNet:
- *Modify* Press Release Ticket (is_media, is_sims && is_comms, is_admin, is_director)
    > On Create of PR Ticket, create a General Release of the title
- *Update* Sims Master Inbox
    > Include Media (all PRs and PCs)
- *Add* Press Conference Ticket
    > IDK....
- *Add* CNN Script Ticket
	> Notifications will be send to USG-M and EIC, who can acknowledge it.
	> IPD’s Chief Communications Officer will be responsible for coordinating all leaks from Sims. Should there be a Sims to Media form for this?

**Comment by ElliottAYoung** [comment]
Sub-Tickets: 
#23 - Add Sims-Focused Media Event to Media Tickets
#24 - Modify Press Release Ticket
#25 - Update Sims Master Inbox to Include all PRs and PCs
#26 - Press Conference Ticket
#27 - Add CNN Script Ticket

**Comment by jessicacorbett** [comment]
Elliott, I see you have "Add Press Conference Ticket > IDK...." Based on Jose's ideas for the Sims Focused Media Event, it seems this needs to be its own ticket. I'm thinking:

Form should include: 1) Parties requested; 2) Suggested time (at least 30 minutes after sent); 3) Location; 4) Full Speaker List; 5) Reason for PC.

– POs can create (at request of cabinet press delegates)
> SIMS back office notified/can acknowledge
> USG-M/EIC notified/can acknowledge
> IPD COO notified/can acknowledge/*CAN CONFIRM* (necessary for it to happen)
> ***IF WE ARE LIVE STREAMING*** CNN Executive Producer should also be notified/ can acknowledge

– IPD COOs can create (at request of IPD press delegates)
> SIMS back office notified/can acknowledge
> USG-M/EIC notified/can acknowledge
> Relevant PO(s) notified/can acknowledge/*CAN CONFIRM* (necessary for it to happen)
> ***IF WE ARE LIVE STREAMING*** CNN Executive Producer should also be notified/ can acknowledge

...thoughts?

**Comment by ElliottAYoung** [comment]
That's just about how I have it, take a look at it on Skynet and let me know if that form works for you?
