### ISSUE TITLE
Add Sims-Focused Media Event to Media Tickets

### ISSUE THREAD

**Issue by ElliottAYoung** [CIMUN/SKYNet#23]

**Comment by ElliottAYoung** [comment]
From Jose:

-- Please explain exactly how you want this to play between your two departments
A SIMS Focused Media Event is a ticket that Media sends to SIMS and vice versa. 
From a Media perspective, it's a notification filing Media sends to SIMS on a "story" that they're working on that they would like SIMS involvement in.

On the SIMS side, it's a Ticket that SIMS sends out to Media on a development we would like the IPD to pick up - this is a direct response to the mess of last year; instead of SIMS commandeering IPD delegates, we'll just send out tickets to Media on what's going on that needs Media involvement. 

Lastly, maybe we can build this into the OmniForm system.
From the Media Side, they can file it as an OmniForm B, requesting SIMS Action on a Media Event.

From the SIMS side, SIMS can file it as an OmniForm C, requesting Media to pick up a story that SIMS is developing.

**Comment by ElliottAYoung** [comment]
On Hold until I get both Jose and Jess to agree on one thing

**Comment by jessicacorbett** [comment]
From the Sims to Media, my read of this is that it allows for leaks/tips from back office – is that correct? It will exist in addition to the PRs and PCs? 

I am not sure what the OmniForm B and C are, so a clarification of that would be great.

For Sims to Media, the USG-M, EIC and COO (Chief Communication Officers aka media liaisons) should be notified. For Media to Sims, Jose?
